name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkout:
    name: Checkout do código da automação
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  clone_smartbeat:
    name: Clonar o repositório SmartBeat
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - run: git clone https://github.com/dennis001/Ambiente-Robot-Web-V1.git smartbit
      - uses: actions/upload-artifact@v4
        with:
          name: smartbit
          path: smartbit

  setup_docker:
    name: Instalar Docker e subir serviços
    runs-on: ubuntu-latest
    needs: clone_smartbeat
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          ls -la
          docker-compose up -d
          echo "Aguardando os serviços subirem..."
          sleep 20
      - run: docker ps -a
      - uses: actions/upload-artifact@v4
        with:
          name: smartbit
          path: smartbit

 # setup_dependencies:
  #  name: Instalar dependências da API e Web
   # runs-on: ubuntu-latest
    #needs: setup_docker
    #steps:
     # - uses: actions/checkout@v4
      #- uses: actions/download-artifact@v4
       # with:
        #  name: smartbit
      #- run: |
       #   cd api
        #  npm install
      #- run: |
       #   cd web
        #  npm install
     # - uses: actions/upload-artifact@v4
      #  with:
       #   name: smartbit
        #  path: smartbit

  setup_api_web:
    name: Rodar setup e subir API/Web
    runs-on: ubuntu-latest
    needs: setup_docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          cd api
          npm install
          chmod +x setup.sh
          ./setup.sh
        continue-on-error: true
#      - uses: actions/upload-artifact@v4
 #       with:
  #        name: smartbit
   #       path: smartbit

 # test:
  #  name: Instalar Robot Framework e Executar Testes
   # runs-on: ubuntu-latest
    #needs: setup_api_web
   # steps:
    #  - uses: actions/checkout@v4
     # - uses: actions/download-artifact@v4
      #  with:
       #   name: smartbit
      - run: |
          cd api
          nohup npm run dev > ../api.log 2>&1 &
      - run: |
          cd web
          nohup npm run dev > ../web.log 2>&1 &
      - run: sleep 20
      - run: docker ps -a    
      - run: |
          pip install robotframework
          pip install -r requirements.txt
          rfbrowser init
      - name: Iniciar Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - run: robot -d results tests/
      - uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
      - uses: actions/upload-artifact@v4
        with:
          name: smartbit
          path: smartbit

  cleanup:
    name: Derrubar os containers do SmartBeat
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          cd smartbit
          docker-compose down
