name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkout:
    name: Checkout do código da automação
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  clone_smartbeat:
    name: Clonar o repositório SmartBeat
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - run: git clone https://github.com/dennis001/Ambiente-Robot-Web-V1.git smartbit
      - uses: actions/upload-artifact@v4
        with:
          name: smartbit
          path: smartbit

  setup_docker:
    name: Instalar Docker e subir serviços
    runs-on: ubuntu-latest
    needs: clone_smartbeat
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - run: |
          cd smartbit
          docker-compose up -d
          echo "Aguardando os serviços subirem..."
          sleep 20
      - run: docker ps -a

  setup_dependencies:
    name: Instalar dependências da API e Web
    runs-on: ubuntu-latest
    needs: setup_docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          cd smartbit/api
          npm install
      - run: |
          cd smartbit/web
          npm install

  setup_api_web:
    name: Rodar setup e subir API/Web
    runs-on: ubuntu-latest
    needs: setup_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          cd smartbit/api
          chmod +x setup.sh
          ./setup.sh
      - run: |
          cd smartbit/api
          nohup npm run dev &
      - run: |
          cd smartbit/web
          nohup npm run dev &
      - run: sleep 20
      - run: docker ps -a

  test:
    name: Instalar Robot Framework e Executar Testes
    runs-on: ubuntu-latest
    needs: setup_api_web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          pip install robotframework
          pip install -r requirements.txt
      - run: robot -d results tests/
      - uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/

  cleanup:
    name: Derrubar os containers do SmartBeat
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: smartbit
      - run: |
          cd smartbit
          docker-compose down
